/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RulesIndexImport } from './routes/rules/index'
import { Route as LogicBlocksIndexImport } from './routes/logic-blocks/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RulesIndexRoute = RulesIndexImport.update({
  path: '/rules/',
  getParentRoute: () => rootRoute,
} as any)

const LogicBlocksIndexRoute = LogicBlocksIndexImport.update({
  path: '/logic-blocks/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logic-blocks/': {
      id: '/logic-blocks/'
      path: '/logic-blocks'
      fullPath: '/logic-blocks'
      preLoaderRoute: typeof LogicBlocksIndexImport
      parentRoute: typeof rootRoute
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/logic-blocks': typeof LogicBlocksIndexRoute
  '/rules': typeof RulesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/logic-blocks': typeof LogicBlocksIndexRoute
  '/rules': typeof RulesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/logic-blocks/': typeof LogicBlocksIndexRoute
  '/rules/': typeof RulesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logic-blocks' | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logic-blocks' | '/rules'
  id: '__root__' | '/' | '/logic-blocks/' | '/rules/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LogicBlocksIndexRoute: typeof LogicBlocksIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LogicBlocksIndexRoute: LogicBlocksIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/logic-blocks/",
        "/rules/"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/logic-blocks/": {
      "filePath": "logic-blocks/index.jsx"
    },
    "/rules/": {
      "filePath": "rules/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
